version: "3.9"
services:
  liexpress:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ${PWD}/config.yaml:/etc/app/config.yaml
    environment:
      - API_KEYS=1234
      - CONFIG_PATH=/etc/app/config.yaml
      - ENV=dev
